
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import util.ArrayFormatter;

import static org.junit.Assert.*;

import java.util.ArrayList;

public class ArrayFormatterTest {
    @Test
    public void testListToArray() {
        int[] expectedArr = { 0, 1, 2 };
        ArrayList<Integer> testList = new ArrayList<>();
        testList.add(0);
        testList.add(1);
        testList.add(2);
        assertArrayEquals(expectedArr, ArrayFormatter.toIntArray(testList));
    }
}