
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import model.*;

public class ParkModelTest {
	@Test
	public void testAppHasAGreeting() {
		ParkModel parkModel = new ParkModel();
		assertNotNull(parkModel);
	}
}